### ISSUE TITLE
FOREST: Add CLEAN toggle to DATASET to remove constant columns and convert char to factor

### ISSUE THREAD

**Issue by yixiangyin** [gjwgit/rattleng#84]
investigate why
<img width="1072" alt="Screenshot 2024-05-13 at 23 35 24" src="https://github.com/gjwgit/rattleng/assets/74629333/26a74687-160d-4900-bcc2-f604fc2bd2ba">

**Comment by yixiangyin** [comment]
<img width="912" alt="Screenshot 2024-05-13 at 23 25 45" src="https://github.com/gjwgit/rattleng/assets/74629333/f7e71564-bd5b-4777-bb28-bb3fca4ca4cc">

**Comment by gjwgit** [comment]
I can replicate the fail if I load the dataset from my own weather.csv file:

![image](https://github.com/gjwgit/rattleng/assets/1681429/ac844755-5e3a-4c55-9f1b-72fbdb0fa794)

But if I run the Demo dataset it works okay?????

![image](https://github.com/gjwgit/rattleng/assets/1681429/18847207-a243-43d8-9a07-bf529900c865)

**Comment by gjwgit** [comment]
The issue is that the demo dataset has the chars as ordinal where as read_csv() keeps them as char.

randomForest() is using na.roughFix() to deal with missing values through na.action and na.roughFix only works for  numeric or factor.

Solution: Add a CLEAN toggle to the dataset page that will remove columns in the data that have a single value, or are all missing, and particularly convert all char to ord.

**Comment by gjwgit** [comment]
Completed as b057084a5307cb9d3b1cf59a095260b6f233f1a8
